services:
  app:
    container_name: app-curso-lb4
    build:
      context: .
    image: app-curso-lb4-imagem
    env_file:
      - ".env"
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: app-curso-mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: app-curso-root
      MONGO_INITDB_ROOT_PASSWORD: app-curso-senha

  mongo-express:
    image: mongo-express
    container_name: app-curso-mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: app-curso-root
      ME_CONFIG_MONGODB_ADMINPASSWORD: app-curso-senhamongo
      ME_CONFIG_MONGODB_URL: mongodb://app-curso-root:app-curso-senha@mongo:27017/
      ME_CONFIG_BASICAUTH: false
